command_timeout = 1000
format = '$azure$kubernetes$all'

# Disable blank line between shell prompts
add_newline = false

# Disable 2-line prompt
[line_break]
disabled = true

# Drop default prompt character
[character]
disabled = true

# Disable previous command status
[status]
disabled = true

# Disable number of jobs running
[jobs]
disabled = true

# Enable Azure in prompt
[azure]
disabled = false
style = 'bold cyan'

# Shows kubernetes context and namespace
[kubernetes]
disabled = false
format = 'via [󱃾 $context\($namespace\)](bold blue) '

# Shows current directory
[directory]
disabled = false
style = 'bold purple'
truncation_symbol = '…/'
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
disabled = false
style = 'bold green'

# Shows current git commit tag
[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = '🏷  '
format = '[\($tag\)]($style) '

# Shows terraform version
[terraform]
disabled = false
format = 'via [󱁢 $version]($style) '
