command_timeout = 1000
format = '$azure$kubernetes$all'

# Enable Azure in prompt
[azure]
disabled = false
style = 'bold cyan'

# Shows kubernetes context and namespace
[kubernetes]
disabled = false
format = 'via [󱃾 $context\($namespace\)](bold blue) '

# Shows current directory
[directory]
disabled = false
style = 'bold purple'
truncation_symbol = '…/'
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
disabled = false
style = 'bold green'

# Shows terraform version
[terraform]
disabled = false
format = 'via [󱁢 $version]($style) '